apiVersion: v1
data:
  env.sh: |
    #!/usr/bin/env bash

    DOMAIN=zk-cluster-headless..svc.cluster.local
    QUORUM_PORT=2888
    LEADER_PORT=3888
    CLIENT_HOST=zk-cluster-client
    CLIENT_PORT=2181
    CLUSTER_NAME=zk-cluster
    CLUSTER_SIZE=3
  log4j-quiet.properties: |
    log4j.rootLogger=ERROR, CONSOLE
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.Threshold=ERROR
    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
  log4j.properties: |
    zookeeper.root.logger=CONSOLE
    zookeeper.console.threshold=INFO
    log4j.rootLogger=${zookeeper.root.logger}
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.Threshold=${zookeeper.console.threshold}
    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
  zoo.cfg: |
    4lw.commands.whitelist=cons, envi, conf, crst, srvr, stat, mntr, ruok
    dataDir=/data
    standaloneEnabled=false
    reconfigEnabled=true
    skipACL=yes
    metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
    metricsProvider.httpPort=7000
    metricsProvider.exportJvmInfo=true
    initLimit=10
    syncLimit=2
    tickTime=2000
    quorumListenOnAllIPs=false
    dynamicConfigFile=/data/zoo.cfg.dynamic
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: zk-cluster-configmap
